services:
  serial_to_websocket:
    build: serial_to_websocket/.
    container_name: serial_to_websocket
    restart: unless-stopped
    devices:
      - "/dev:/dev"
#    privileged: true # Grants extended privileges (use with caution)
    ports:
      - "9001:9001"  # Expose the WebSocket server port
    network_mode: bridge


  air_pressure:
    build: air_pressure/.
    container_name: air_pressure
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    network_mode: bridge