services:
  broker:
    image: eclipse-mosquitto:latest
    container_name: broker

    # Expose the MQTT port
    ports:
      - "1883:1883"

    # Copy the configuration file to the container
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  data_forwarder:
    build:
        context: .
        dockerfile: Dockerfile
    privileged: true
    container_name: serial_data_forwarder
    environment:
      MQTT_BROKER: broker

    devices:
      - "/dev:/dev"